### ISSUE TITLE
Deployment: Receive TypeError: Cannot read property 'rendered' of undefined

### ISSUE THREAD

**Issue by jacobmishkin** [postlight/headless-wp-starter#112]
After using the command yarn run deploy, I get the following error: 

yarn run v1.6.0
$ yarn run docker:build && yarn run docker:clean && yarn run docker:run
$ docker build -t frontend .
Sending build context to Docker daemon  712.7kB
Step 1/9 : FROM node:7
 ---> d9aed20b68a4
Step 2/9 : RUN mkdir -p /usr/src/app
 ---> Using cache
 ---> 23cb25d6a681
Step 3/9 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 9b73d7f19494
Step 4/9 : COPY package.json /usr/src/app/
 ---> Using cache
 ---> 6ae38ba31174
Step 5/9 : RUN npm install
 ---> Using cache
 ---> 617b15f34d6f
Step 6/9 : COPY . /usr/src/app
 ---> cef3b67ace52
Step 7/9 : RUN npm run build
 ---> Running in 01787c3bc9bd
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.10.1
npm info lifecycle frontend@1.0.0~prebuild: frontend@1.0.0
npm info lifecycle frontend@1.0.0~build: frontend@1.0.0

> frontend@1.0.0 build /usr/src/app
> next build

npm info lifecycle frontend@1.0.0~postbuild: frontend@1.0.0
npm info ok
Removing intermediate container 01787c3bc9bd
 ---> d2cf1756b0b7
Step 8/9 : EXPOSE 3000
 ---> Running in 96c8c6fcbae6
Removing intermediate container 96c8c6fcbae6
 ---> 66c882bdc86e
Step 9/9 : CMD [ "npm", "start" ]
 ---> Running in eeb6b977bdea
Removing intermediate container eeb6b977bdea
 ---> af65397fcaf4
Successfully built af65397fcaf4
Successfully tagged frontend:latest
$ docker rm -f frontend || true
frontend
$ docker run -p 3000:3000 --name frontend frontend
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.10.1
npm info lifecycle frontend@1.0.0~prestart: frontend@1.0.0
npm info lifecycle frontend@1.0.0~start: frontend@1.0.0

> frontend@1.0.0 start /usr/src/app
> node server.js

 DONE  Compiled successfully in 1551ms6:10:33 PM

> Ready on http://localhost:3000
Client pings, but there's no entry for page: /
> Building page: /
 DONE  Compiled successfully in 3410ms6:10:39 PM

 WAIT  Compiling...6:10:40 PM

 DONE  Compiled successfully in 100ms6:10:40 PM

{ TypeError: Cannot read property 'rendered' of undefined
    at Index.render (pages/index.js:46:0)
    at processChild (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2204:18)
    at resolve (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2061:5)
    at ReactDOMServerRenderer.render (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2380:22)
    at ReactDOMServerRenderer.read (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2354:19)
    at renderToString (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2726:25)
    at renderPage (/usr/src/app/node_modules/next/dist/server/render.js:275:26)
    at Function.getInitialProps (/usr/src/app/node_modules/next/dist/server/document.js:67:25)
    at _callee$ (/usr/src/app/node_modules/next/dist/lib/utils.js:111:30)
    at tryCatch (/usr/src/app/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/src/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/usr/src/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
    at /usr/src/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:34:7
    at F (/usr/src/app/node_modules/core-js/library/modules/_export.js:36:28) sourceMapsApplied: true }

I have a running subdomain WP install that I imported from my local WP install.  I changed the config file to mach the live WP install. Is there a step that I am missing? 

Side note, working locally does not work as well. the WP site locally will run, but not the frontend. I receive the same error locally as well. Thanks in advance.

**Comment by jacobmishkin** [comment]
Please feel free to close this issue, as I have fixed the issue. Thanks!

**Comment by ginatrapani** [comment]
thanks @jacobmishkin -- curious: what was the fix?

**Comment by jacobmishkin** [comment]
Rookie mistake. Imported the database, but not the theme to the live WP install. This theme has been really great to use, by the way. Thanks!
