### ISSUE TITLE
Uncaught Error: Class 'WPGraphQL\Data\Config' not found

### ISSUE THREAD

**Issue by Prusdrum** [postlight/headless-wp-starter#127]
I'm having an issue trying to run yarn docker:start

wp commands seem to run correctly 
I can see for example: :heavy_check_mark: 
```
Plugin 'acf-to-wp-api' activated.
Plugin 'advanced-custom-fields-pro' activated.
Plugin 'custom-post-type-ui' activated.
Plugin 'wp-graphql' activated.
Plugin 'wp-migrate-db-pro' activated.
Plugin 'wp-migrate-db-pro-cli' activated.
Plugin 'wp-migrate-db-pro-media-files' activated.
Plugin 'wp-rest-api-v2-menus' activated.
Success: Activated 8 of 8 plugins.
```
but then other errors start to show :x: 
```
PHP Warning:  include(/usr/src/app/wordpress/wp-content/plugins/wp-graphql/vendor/composer/../../src/Data/Config.php): failed to open stream:No such file or directory in phar:///usr/local/bin/wp/vendor/composer/ClassLoader.php on line 444
Warning: include(/usr/src/app/wordpress/wp-content/plugins/wp-graphql/vendor/composer/../../src/Data/Config.php): failed to open stream: No such file or directory in phar:///usr/local/bin/wp/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(): Failed opening '/usr/src/app/wordpress/wp-content/plugins/wp-graphql/vendor/composer/../../src/Data/Config.php' for inclusion (include_path='.:/usr/share/php') in phar:///usr/local/bin/wp/vendor/composer/ClassLoader.php on line 444
Warning: include(): Failed opening '/usr/src/app/wordpress/wp-content/plugins/wp-graphql/vendor/composer/../../src/Data/Config.php' for inclusion (include_path='.:/usr/share/php') in phar:///usr/local/bin/wp/vendor/composer/ClassLoader.php on line 444
PHP Fatal error:  Uncaught Error: Class 'WPGraphQL\Data\Config' not found in /usr/src/app/wordpress/wp-content/plugins/wp-graphql/wp-graphql.php:227
Stack trace:
#0 /usr/src/app/wordpress/wp-includes/class-wp-hook.php(286): WPGraphQL->{closure}('')
#1 /usr/src/app/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /usr/src/app/wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /usr/src/app/wordpress/wp-settings.php(434): do_action('after_setup_the...')
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1188): require('/usr/src/app/wo...')
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1111): WP_CLI\Runner->load_wordpress()
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/ph in /usr/src/app/wordpress/wp-content/plugins/wp-graphql/wp-graphql.php on line 227
Fatal error: Uncaught Error: Class 'WPGraphQL\Data\Config' not found in /usr/src/app/wordpress/wp-content/plugins/wp-graphql/wp-graphql.php:227
Stack trace:
#0 /usr/src/app/wordpress/wp-includes/class-wp-hook.php(286): WPGraphQL->{closure}('')
#1 /usr/src/app/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /usr/src/app/wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /usr/src/app/wordpress/wp-settings.php(434): do_action('after_setup_the...')
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1188): require('/usr/src/app/wo...')
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1111): WP_CLI\Runner->load_wordpress()
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/ph in /usr/src/app/wordpress/wp-content/plugins/wp-graphql/wp-graphql.php on line 227
```
:gear: 
I'm running mysql as a separate container
Ubuntu 18.04.1 LTS
Docker version 18.06.0-ce, build 0ffa825

**Comment by Prusdrum** [comment]
btw - everything works fine after I completely removed `/wordpress/wp-content/plugins/wp-graphql/`

**Comment by modelm** [comment]
The latest wp-graphql doesn't seem to suffer from this problem, but feel free to re-open if you see this error again.
