### ISSUE TITLE
Menu won't load

### ISSUE THREAD

**Issue by mahayne** [postlight/headless-wp-starter#156]
I really want this to work! I've worked through several issues around ports in use, needing to set permalinks to get past the redirect errors, and not having a "welcome" page - more info on these should be in the docs - could save you some extra issue responses!

Now I am getting this error in the FRONTEND (backend is directing to /wp-json with no errors), and can't find a solution - the menu items are undefined it seems:
**TypeError: Cannot read property 'map' of undefined**
    at Menu.render (/Users/maryh/Sites/postlight/frontend/.next/server/static/development/pages/index.js:301:45)
    at processChild (/Users/maryh/Sites/postlight/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2861:18)
    at resolve (/Users/maryh/Sites/postlight/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2714:5)
    at ReactDOMServerRenderer.render (/Users/maryh/Sites/postlight/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3098:22)
    at ReactDOMServerRenderer.read (/Users/maryh/Sites/postlight/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3057:29)
    at renderToString (/Users/maryh/Sites/postlight/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3524:27)
    at renderPage (/Users/maryh/Sites/postlight/frontend/node_modules/next/dist/server/render.js:319:26)
    at Function.getInitialProps (/Users/maryh/Sites/postlight/frontend/node_modules/next/dist/server/document.js:65:25)
    at _callee$ (/Users/maryh/Sites/postlight/frontend/node_modules/next/dist/lib/utils.js:86:30)
    at tryCatch (/Users/maryh/Sites/postlight/frontend/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/maryh/Sites/postlight/frontend/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/maryh/Sites/postlight/frontend/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/maryh/Sites/postlight/frontend/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/Users/maryh/Sites/postlight/frontend/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
    at /Users/maryh/Sites/postlight/frontend/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)

There is a menu, and it has two pages on it - Home and Welcome :)
I am not able to find where the menu items property is defined.

Thanks in advance!

**Comment by mahayne** [comment]
Needed to install menu plugin, but also found that can add the endpoint and punt on the plugin.
