### ISSUE TITLE
Issue adding Pose animations

### ISSUE THREAD

**Issue by annamirakk** [postlight/headless-wp-starter#180]
I'm trying to use [Pose](https://popmotion.io/pose/) to add animations to my project. I've installed the package in the frontend directory with `yarn add react-pose` per [instructions](https://popmotion.io/pose/learn/install/), and when I add `react-pose` to the page in index.js, I immediately get this error:

```
React.createContext is not a function
TypeError: React.createContext is not a function
    at Object.<anonymous> (/var/www/html/frontend/node_modules/react-pose/lib/index.js:46:16)
    at Module._compile (module.js:652:30)
    at Module._compile (/var/www/html/frontend/node_modules/source-map-support/source-map-support.js:492:25)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/frontend/pages/index.js:9:1)
```

Help is much appreciated! If there's a different animation library that works well with this kit, I'd also appreciate a link, thanks!

**Comment by jacobmishkin** [comment]
Hi Ann, 

It maybe because you are using the default react 16.0.0 version, not react 16.3.0 or higher. to fix this in your frontend folder, go to your package.json file and change the react version number. Then do a yarn install, you should be good to go. createContext does not exist in react version 16.0.0.

**Comment by modelm** [comment]
fixed in https://github.com/postlight/headless-wp-starter/blob/feat-dockerer/frontend/package.json
