### ISSUE TITLE
Randomly receiving errors with Webpack when compiling server side code

### ISSUE THREAD

**Issue by GInTher** [postlight/headless-wp-starter#208]
There have been intermittent issues when running yarn start on the front-end. Looks like it's been having issues compiling the server-side code from Webpack

`
adams-mbp:frontend adam$ yarn start
yarn run v1.6.0
$ CHOKIDAR_USEPOLLING=true node server.js

Compiling

● client

● server █████████████████████████ compiling (0%)  
 

/Users/adam/repos/headless-wp-starter/frontend/node_modules/webpack/lib/ProgressPlugin.js:205
                                compilation.hooks.addEntry.tap("ProgressPlugin", entryAdd);
                                                           ^

TypeError: Cannot read property 'tap' of undefined
    at compiler.hooks.compilation.tap.compilation (/Users/adam/repos/headless-wp-starter/frontend/node_modules/webpack/lib/ProgressPlugin.js:205:32)
    at SyncHook.eval [as call] (eval at create (/Users/adam/repos/headless-wp-starter/frontend/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (/Users/adam/repos/headless-wp-starter/frontend/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/adam/repos/headless-wp-starter/frontend/node_modules/next/node_modules/webpack/lib/Compiler.js:498:26)
    at hooks.beforeCompile.callAsync.err (/Users/adam/repos/headless-wp-starter/frontend/node_modules/next/node_modules/webpack/lib/Compiler.js:534:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/adam/repos/headless-wp-starter/frontend/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/adam/repos/headless-wp-starter/frontend/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/adam/repos/headless-wp-starter/frontend/node_modules/next/node_modules/webpack/lib/Compiler.js:529:28)
    at compiler.hooks.watchRun.callAsync.err (/Users/adam/repos/headless-wp-starter/frontend/node_modules/next/node_modules/webpack/lib/Watching.js:77:18)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/adam/repos/headless-wp-starter/frontend/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/adam/repos/headless-wp-starter/frontend/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._go (/Users/adam/repos/headless-wp-starter/frontend/node_modules/next/node_modules/webpack/lib/Watching.js:40:32)
    at Watching.compiler.readRecords.err (/Users/adam/repos/headless-wp-starter/frontend/node_modules/next/node_modules/webpack/lib/Watching.js:32:9)
    at Array.inputFileSystem.stat.err (/Users/adam/repos/headless-wp-starter/frontend/node_modules/next/node_modules/webpack/lib/Compiler.js:401:20)
    at Storage.finished (/Users/adam/repos/headless-wp-starter/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/Users/adam/repos/headless-wp-starter/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by devdarren7** [comment]
also getting this ..did you solve?

**Comment by devdarren7** [comment]
ok I fixed it , you have to remove the webpack dev dependency from the package.json file , then run yarn again 

Brain fart from here : https://stackoverflow.com/questions/53227877/progressplugin-typeerror-cannot-read-property-tap-of-undefined
