### ISSUE TITLE
Frontend yarn run dev Error: Couldn't find preset "react-native" relative to directory

### ISSUE THREAD

**Issue by WebRuin** [postlight/headless-wp-starter#64]
After cloning the repo I di the following steps:

`yarn install && yarn start`
`cd frontend && yarn install && yarn run dev`

When I go to `localhost:3000` I get:

Error in /home/tithos/Web/react/nohead/frontend/pages/index.js?entry
Module build failed: Error: Couldn't find preset "react-native" relative to directory "/home/tithos/Web"
    at /home/tithos/Web/react/nohead/frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/home/tithos/Web/react/nohead/frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/tithos/Web/react/nohead/frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/tithos/Web/react/nohead/frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/tithos/Web/react/nohead/frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/tithos/Web/react/nohead/frontend/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/tithos/Web/react/nohead/frontend/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/tithos/Web/react/nohead/frontend/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/tithos/Web/react/nohead/frontend/node_modules/next/node_modules/babel-loader/lib/index.js:50:20)

Ubuntu

Tim

**Comment by tristanoneil** [comment]
This seems similar to https://github.com/postlight/headless-wp-starter/issues/99 ? Can you confirm that you don't have a `node_modules` directory at the same level as this repo?
