### ISSUE TITLE
TypeError: Cannot read property 'rendered' of undefined

### ISSUE THREAD

**Issue by brandonpowell** [postlight/headless-wp-starter#76]
When I was change likes pages names to like Home, About, Blog Contact page's. I'm getting this error message that said. I have not touch `index.js` but only WP Back-end. 

```Cannot read property 'rendered' of undefined
TypeError: Cannot read property 'rendered' of undefined
    at Index.render (/Users/mirasmith/Desktop/wp__ireconcile/frontend/pages/index.js:59:13)
    at resolve (/Users/mirasmith/Desktop/wp__ireconcile/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2149:18)
    at ReactDOMServerRenderer.render (/Users/mirasmith/Desktop/wp__ireconcile/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2260:22)
    at ReactDOMServerRenderer.read (/Users/mirasmith/Desktop/wp__ireconcile/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2234:19)
    at renderToString (/Users/mirasmith/Desktop/wp__ireconcile/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:2501:25)
    at renderPage (/Users/mirasmith/Desktop/wp__ireconcile/frontend/node_modules/next/dist/server/render.js:174:26)
    at Function.getInitialProps (/Users/mirasmith/Desktop/wp__ireconcile/frontend/node_modules/next/dist/server/document.js:83:25)
    at _callee$ (/Users/mirasmith/Desktop/wp__ireconcile/frontend/node_modules/next/dist/lib/utils.js:36:30)
    at tryCatch (/Users/mirasmith/Desktop/wp__ireconcile/frontend/node_modules/next/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/mirasmith/Desktop/wp__ireconcile/frontend/node_modules/next/node_modules/regenerator-runtime/runtime.js:299:22)```

**Comment by glrodasz** [comment]
The frontend project is expecting a basic structure of pages. So you need to be careful an review what the frontend is requiring. You can check the API request that the pages are doing in the `pages` folder. and comment them temporary.
